# abbu

ASLMODADD=	MAIN_ASLTS
AMLMOD= extra extra_aslts
COLL= ../..

ADD_ASLFLAGS=-vx 6142 #illegal forward reference
ADD_ASLFLAGS+=-vx 6152 #recursive method call

TOP= $(COLL)/../../..
include $(COLL)/Makefile.install
