#!/bin/bash
#
# acpipkg
#
# This script generates patches, tars, and executables, for
# distribution.
#
#

pushd ~

DATE=`date +%Y%m%d`

echo Removing old files in output/
rm -rf output/*

echo generating tar and diff
receive
tar czf output/acpica-linux-$DATE.tar.gz linux/drivers/acpi linux/include/linux/acpi.h
diff -Naur -X bin/dontdiff /usr/src/linux linux > output/acpi-$DATE.diff
gzip output/acpi-$DATE.diff

echo generating other-files diff
# generate other-files diff
diff -Naur -X bin/dontdiff /usr/src/linux/Documentation/Configure.help linux/Documentation/Configure.help > output/acpi-other-files-$DATE.diff
diff -Naur -X bin/dontdiff /usr/src/linux/Makefile linux/Makefile >> output/acpi-other-files-$DATE.diff
diff -Naur -X bin/dontdiff /usr/src/linux/include/linux linux/include/linux >> output/acpi-other-files-$DATE.diff
diff -Naur -X bin/dontdiff /usr/src/linux/arch/i386 linux/arch/i386 >> output/acpi-other-files-$DATE.diff
diff -Naur -X bin/dontdiff /usr/src/linux/arch/ia64 linux/arch/ia64 >> output/acpi-other-files-$DATE.diff
gzip output/acpi-other-files-$DATE.diff

mkdir -p output/temp
echo Making Linux iasl
cp /root/desk/acpica-unix-$DATE.tar.gz output/temp
cd output/temp
tar xzf acpica-unix-$DATE.tar.gz
cd compiler
make >/dev/null
cp iasl ~/output
cd ~/
rm -rf output/temp

popd

