 
PROG=	acpibin
SRCS=	abcompare.c abmain.c \
	../../utilities/utalloc.c \
	../../utilities/utdebug.c \
	../../utilities/utglobal.c \
	../../utilities/utmath.c \
	../../utilities/utmisc.c \
	../../osunixxf.c \
    ../../common/getopt.c

CFLAGS+= -Wall -O2 -D_LINUX -Wstrict-prototypes -I../../include 


acpibin : $(patsubst %.c,%.o, $(SRCS))
	$(CC) $(LDFLAGS) $(patsubst %.c,%.o, $(SRCS)) -o $(PROG)

CLEANFILES= $(PROG)

clean : 
	rm -f $(CLEANFILES) $(patsubst %.c,%.o, $(SRCS))

