 

PROG=	acpisrc
SRCS=	ascase.c asconvrt.c asfile.c asmain.c asremove.c asutils.c osunixdir.c \
        ../../common/getopt.c

CFLAGS+= -Wall -O2 -Wstrict-prototypes -D_LINUX -I../../include 


aslmain : $(patsubst %.c,%.o, $(SRCS))
	$(CC) $(LDFLAGS) $(patsubst %.c,%.o, $(SRCS)) \
		$(LOADLIBES) $(LDLIBS) -o iasl

CLEANFILES= acpisrc

clean : 
	rm -f $(CLEANFILES) $(patsubst %.c,%.o, $(SRCS))

